### ISSUE TITLE
encryptFileSync

### ISSUE THREAD

**Issue by u007** [onmodulus/file-encryptor#3]
Hi,

do you have a encryptFile which waits for the file to be processed?
it would be very helpful..

**Comment by tzmanics** [comment]
Hi @u007 sorry for the delay. We don't have that at the moment and we aren't currently maintaining this repo so I'm going to close this issue for now. Once we figure out the next steps for `file-encryptor` we'll update the repo.

Thanks for reaching out and feel free to re-open this issue if it's something you would like addressed sooner rather than later.

**Comment by u007** [comment]
okay thank you
